### ISSUE TITLE
FEATURE REQUEST: Auto-adjustment of start date

### ISSUE THREAD

**Issue by eliaslm** [Northo/ny-launcher#2]
# 🔙 Start date isn't automatically adjusted if the end date is set to be before the start date
See title 🤝 Not a huge deal, but it would be super convenient if the start date automatically adjusted to the day before the selected end date, if the end date is set to be before the selected start date 😌 Let me know if you think this would be a cool feature 🗳️

**Comment by Northo** [comment]
@eliaslm, we went for instead adjusting the allowed range to before/after the other date. Let me know how you like that!
